Feature: implement nonce for creating payment intent
impress-org/donation-block-for-stripe pull request #7
Opened 2022-03-03 19:23 UTC by JasonTheAdams

Resolves #1 

## Description

This adds a nonce to creating a Payment Intent, protecting sites from malicious abuse of the endpoint.

As part of this, I also fixed how error messages are displayed, differentiating between the server sending a single message versus an array of fields with errors.

## Affects

When the form is submitted and a payment intent is created to display the CC fields.

## Testing Instructions

Just make a donation. If it works, the nonce works.

To test the errors go into the `PaymentIntentRequest` class and force the errors to happen.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

2022-03-03 19:52 UTC, DevinWalker requested changes
Error handling needs some work on step 2

2022-03-03 19:52 UTC, DevinWalker commented on src/donationForm.js
> -                                {error && (
@JasonTheAdams this error output needs to be in place. Without it, messages from the Stripe API about the payment method in use are not displayed. For instance:

**Current develop branch**
<img width="730" alt="2022-03-03_11-48-32" src="https://user-images.githubusercontent.com/1571635/156642122-1a31f57a-1e35-4cf5-bae0-f5b09c3ab5a4.png">

**In this Branch**
<img width="711" alt="2022-03-03_11-51-19" src="https://user-images.githubusercontent.com/1571635/156642130-3414dc13-335f-47b0-9aa5-822a394b6238.png">

2022-03-04 01:05 UTC, JasonTheAdams commented
@DevinWalker Ready for another review!

2022-03-04 01:37 UTC, DevinWalker approved these changes
Works like a charm! 
<img width="706" alt="2022-03-03_17-36-50" src="https://user-images.githubusercontent.com/1571635/156682504-3ff552da-2d91-431c-9ddb-6e2732add119.png">

2022-03-04 01:37 UTC, merged